config/routes.rb
Rails.application.routes.draw do
  resources :courses
  get 'dashboard/index'
  get 'profile/index'
  resources :citytowns do
    resources :schools
      
  end
  
  resources :materials
  get 'accounted/student'
  get 'accounted/teacher'
  get 'accounted/team'
  resources :levels
  root to:'homes#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/dashboard/shared/profs/_sidebar.html.erb
<nav class="w-24 flex flex-col bg-blue-500 hover:text-blue-500 ">
    <!-- Left side NavBar -->
    <div class="">
      <!-- App Logo -->
     	<%= link_to root_path, class:"flex flex-col items-center" do %>
        	<span class="font-bold text-black hover:no-underline ">LNCLASS</span>

     	<% end %>
    </div>

	    <span class="mt-2  capitalize">
		    <ul class="mt-3 p-2  rounded-lg">
			    <%= link_to  new_course_path, class:"flex items-center" do %>
				<span class="font-semibold text-black"> Resumé</span>
				<% end %>
            </ul>
		
		<ul class="mt-3 p-2 text-black rounded-lg">
            <%= link_to new_level_path, class:"flex items-center" do %>
                
               <span class="font-semibold text-black">Voir Resumés</span>
            <% end %>
		</ul>
		<ul class="mt-3 p-2 text-black rounded-lg">
            <%= link_to new_material_path, class:"flex  items-center" do %>
                <span class="font-semibold text-black"> Execices</span>
            <% end %>
		</ul>
		<ul class="mt-3 p-2 text-black rounded-lg">
            <%= link_to new_material_path, class:"flex  items-center" do %>
                <span class="font-semibold text-black"> Voir Execices</span>
            <% end %>
		</ul>
	</span>

	<!-- sign out -->
	<div class="mt-auto flex items-center p-2 text-black-700">
	<!-- important action -->
		<%= link_to destroy_user_session_path, method: :delete do %>
			<i class="fa fa-power-off" aria-hidden="true"></i>Déconnecter
      	<% end %>
	</div>
</nav>