config/routes.rb
Rails.application.routes.draw do
  resources :courses
  get 'dashboard/index'
  get 'profile/index'
  resources :citytowns do
    resources :schools
      
  end
  
  resources :materials
  get 'accounted/student'
  get 'accounted/teacher'
  get 'accounted/team'
  resources :levels
  root to:'homes#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/citytown.rb
class Citytown < ApplicationRecord
  belongs_to :user
  has_many :schools, dependent: :destroy


  #PRESENTE
  validates :title,
            :slug,
             presence: true
  
  ################## VALIDATES  ###############
  validates :title, length: { maximum:50 }
  

  ################## SLUG ###############
  extend FriendlyId
    friendly_id :title, use: :slugged

  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/controllers/citytowns_controller.rb
class CitytownsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_citytown, only: %i[ show edit update destroy ]

  # GET /citytowns or /citytowns.json
  def index
    @citytowns = Citytown.all
  end

  # GET /citytowns/1 or /citytowns/1.json
  def show
  end

  # GET /citytowns/new
  def new
    @citytown = Citytown.new
  end

  # GET /citytowns/1/edit
  def edit
  end

  # POST /citytowns or /citytowns.json
  def create
    @citytown = current_user.citytowns.build(citytown_params)

    respond_to do |format|
      if @citytown.save
        format.html { redirect_to @citytown, notice: "Citytown was successfully created." }
        format.json { render :show, status: :created, location: @citytown }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @citytown.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /citytowns/1 or /citytowns/1.json
  def update
    respond_to do |format|
      if @citytown.update(citytown_params)
        format.html { redirect_to @citytown, notice: "Citytown was successfully updated." }
        format.json { render :show, status: :ok, location: @citytown }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @citytown.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /citytowns/1 or /citytowns/1.json
  def destroy
    @citytown.destroy
    respond_to do |format|
      format.html { redirect_to citytowns_url, notice: "Citytown was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_citytown
      @citytown = Citytown.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def citytown_params
      params.require(:citytown).permit(:title, :slug, :user_id)
    end
end

app/helpers/citytowns_helper.rb
module CitytownsHelper
end

app/views/citytowns/_form.html.erb
<%= form_with(model: citytown, local: true) do |form| %>
  <% if citytown.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(citytown.errors.count, "error") %> prohibited this citytown from being saved:</h2>

      <ul>
        <% citytown.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field my-2">
    <%= form.text_field :title, placeholder:"Nom de la ville ..." %>
  </div>

  <div class="actions mt-2">
    <%= form.submit "Add new city", class:'inline-flex justify-center py-2 px-4 border border-transparent 
  shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600
 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2
  focus:ring-indigo-500' %>
  </div>
<% end %>

app/views/citytowns/edit.html.erb
<div class="mt-24 mx-6">

<h1>Editing Citytown</h1>

<%= render 'form', citytown: @citytown %>

<%= link_to 'Show', @citytown %> |
<%= link_to 'Liste villes', citytowns_path %>

</div>

app/views/citytowns/index.html.erb
<!-- component -->
<div class="overflow-x-auto">
    <div class="min-w-screen min-h-screen bg-gray-100 flex items-center justify-center bg-gray-100
     font-sans overflow-hidden">
        <div class="w-full lg:w-5/6">
<%= link_to 'Ajouter une ville', new_citytown_path, class:"inline-flex justify-center py-2 px-4 border border-transparent 
  shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600
 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2
  focus:ring-indigo-500" %>
            <div class="bg-white shadow-md rounded ">
                <table class="min-w-max w-full table-auto">
                    <thead>
                        <tr class="bg-gray-200 text-gray-600 text-sm leading-normal">
                            <th class="py-3 px-6 text-left">Villes</th>
                            <th class="py-3 px-6 text-left">City Manager</th>
                            <th class="py-3 px-6 text-center">Profs Part</th>
                            <th class="py-3 px-6 text-center">Status</th>
                            <th class="py-3 px-6 text-center">Options</th>
                        </tr>
                    </thead>
                <% @citytowns.each do |city| %>
                    <tbody class="text-gray-600 text-sm font-light">
                        <tr class="border-b border-gray-200 hover:bg-gray-100">
                            <td class="py-3 px-6 text-left whitespace-nowrap">
                                <div class="flex items-center">
                                    <div class="mr-2">
                                        <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
                                                 width="24" height="24"
                                                 viewBox="0 0 48 48"
                                                 style=" fill:#000000;">
                                            <path fill="#80deea" d="M24,34C11.1,34,1,29.6,1,24c0-5.6,10.1-10,23-10c12.9,0,23,4.4,23,10C47,29.6,36.9,34,24,34z M24,16	c-12.6,0-21,4.1-21,8c0,3.9,8.4,8,21,8s21-4.1,21-8C45,20.1,36.6,16,24,16z"></path><path fill="#80deea" d="M15.1,44.6c-1,0-1.8-0.2-2.6-0.7C7.6,41.1,8.9,30.2,15.3,19l0,0c3-5.2,6.7-9.6,10.3-12.4c3.9-3,7.4-3.9,9.8-2.5	c2.5,1.4,3.4,4.9,2.8,9.8c-0.6,4.6-2.6,10-5.6,15.2c-3,5.2-6.7,9.6-10.3,12.4C19.7,43.5,17.2,44.6,15.1,44.6z M32.9,5.4	c-1.6,0-3.7,0.9-6,2.7c-3.4,2.7-6.9,6.9-9.8,11.9l0,0c-6.3,10.9-6.9,20.3-3.6,22.2c1.7,1,4.5,0.1,7.6-2.3c3.4-2.7,6.9-6.9,9.8-11.9	c2.9-5,4.8-10.1,5.4-14.4c0.5-4-0.1-6.8-1.8-7.8C34,5.6,33.5,5.4,32.9,5.4z"></path><path fill="#80deea" d="M33,44.6c-5,0-12.2-6.1-17.6-15.6C8.9,17.8,7.6,6.9,12.5,4.1l0,0C17.4,1.3,26.2,7.8,32.7,19	c3,5.2,5,10.6,5.6,15.2c0.7,4.9-0.3,8.3-2.8,9.8C34.7,44.4,33.9,44.6,33,44.6z M13.5,5.8c-3.3,1.9-2.7,11.3,3.6,22.2	c6.3,10.9,14.1,16.1,17.4,14.2c1.7-1,2.3-3.8,1.8-7.8c-0.6-4.3-2.5-9.4-5.4-14.4C24.6,9.1,16.8,3.9,13.5,5.8L13.5,5.8z"></path><circle cx="24" cy="24" r="4" fill="#80deea"></circle>
                                        </svg>
                                    </div>
                                    <span class="font-medium"> <%= city.title %></span>
                                </div>
                            </td>
                            <td class="py-3 px-6 text-left">
                                <div class="flex items-center">
                                    <div class="mr-2">
                                       <img class="w-6 h-6 rounded-full" src="https://randomuser.me/api/portraits/men/1.jpg"/>
                                    </div>
                                    <span><%= city.user.full_name %></span>
                                </div>
                            </td>
                            <td class="py-3 px-6 text-center">
                                <div class="flex items-center justify-center">
                                    <img class="w-6 h-6 rounded-full border-gray-200 border transform hover:scale-125" src="https://randomuser.me/api/portraits/men/1.jpg"/>
                                    <img class="w-6 h-6 rounded-full border-gray-200 border -m-1 transform hover:scale-125" src="https://randomuser.me/api/portraits/women/2.jpg"/>
                                    <img class="w-6 h-6 rounded-full border-gray-200 border -m-1 transform hover:scale-125" src="https://randomuser.me/api/portraits/men/3.jpg"/>
                                </div>
                            </td>
                            <td class="py-3 px-6 text-center">
                                <span class="bg-purple-200 text-purple-600 py-1 px-3 rounded-full text-xs">Active</span>
                            </td>
                            <td class="py-3 px-6 text-center">
                                <div class="flex item-center justify-center">
                                    <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                        <%= link_to  city  do %>
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                                            </svg>
                                       <% end %>
                                    </div>
                                    <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                        <%= link_to edit_citytown_path(city) do %>
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                                            </svg>
                                        <% end %>
                                        
                                        </div>
                                        <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                            <%= link_to city, method: :delete, data: { confirm: 'Vous allez supprimé definitivement?' } do %>
                                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                                </svg>
                                                
                                            <% end %>
                                                
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    <% end %>
                    </table>
                </div>
            </div>
        </div>
    </div>

app/views/citytowns/new.html.erb
<div class="container mt-24 mx-6">
<h1>Nouvelle ville</h1>

<%= render 'form', citytown: @citytown %>

<%= link_to 'Liste villes', citytowns_path %>

</div>

app/views/citytowns/show.html.erb
<div class="container mt-24 mx-6">
  <p id="notice"><%= notice %></p>

  <p class="mb-8">
    <strong>Ville:</strong>
    <%= @citytown.title %>  
    <%= link_to 'Nouvelle Ecole', new_citytown_school_path(@citytown), class:"btn btn-primary mx-auto" %>
  </p>


<div class="row">
  <div class="col-12 col-md-4 col-lg-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Special title treatment</h5>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
    </div>
  </div>
  <div class="col-12 col-md-4 col-lg-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Special title treatment</h5>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
    </div>
  </div>
  <div class="col-12 col-md-4 col-lg-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Special title treatment</h5>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
    </div>
  </div>
</div>

  <%= link_to 'Editer', edit_citytown_path(@citytown) %> |
  <%= link_to 'Liste villes', citytowns_path %>
</div>