config/routes.rb
Rails.application.routes.draw do
  resources :courses
  get 'dashboard/index'
  get 'profile/index'
  resources :citytowns do
    resources :schools
      
  end
  
  resources :materials
  get 'accounted/student'
  get 'accounted/teacher'
  get 'accounted/team'
  resources :levels
  root to:'homes#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/level.rb
class Level < ApplicationRecord
  belongs_to :user
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_level, only: %i[ show edit update destroy ]

  # GET /levels or /levels.json
  def index
    @levels = Level.all
  end

  # GET /levels/1 or /levels/1.json
  def show
  end

  # GET /levels/new
  def new
    @level = Level.new
  end

  # GET /levels/1/edit
  def edit
  end

  # POST /levels or /levels.json
  def create
    @level = current_user.levels.build(level_params)

    respond_to do |format|
      if @level.save
        format.html { redirect_to @level, notice: "Level was successfully created." }
        format.json { render :show, status: :created, location: @level }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /levels/1 or /levels/1.json
  def update
    respond_to do |format|
      if @level.update(level_params)
        format.html { redirect_to @level, notice: "Level was successfully updated." }
        format.json { render :show, status: :ok, location: @level }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /levels/1 or /levels/1.json
  def destroy
    @level.destroy
    respond_to do |format|
      format.html { redirect_to levels_url, notice: "Level was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_level
      @level = Level.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def level_params
      params.require(:level).permit(:title, :slug, :user_id)
    end
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/views/levels/_form.html.erb
<%= form_with(model: level, local: true) do |form| %>
  <% if level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(level.errors.count, "error") %> prohibited this level from being saved:</h2>

      <ul>
        <% level.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field my-2">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions mt-2">
    <%= form.submit "Ajoute Niveau", class:'inline-flex justify-center py-2 px-4 border border-transparent 
  shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600
 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2
  focus:ring-indigo-500' %>
  </div>
<% end %>

app/views/levels/edit.html.erb
<h1>Editing niveau</h1>

<%= render 'form', level: @level %>

<%= link_to 'Affiche', @level %> |
<%= link_to 'Retour', levels_path %>

app/views/levels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Levels</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Adresse</th>
      <th>Auteur</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @levels.each do |level| %>
      <tr>
        <td><%= level.title %></td>
        <td><%= level.slug %></td>
        <td><%= level.user_id %></td>
        <td><%= link_to 'Show', level %></td>
        <td><%= link_to 'Edit', edit_level_path(level) %></td>
        <td><%= link_to 'Destroy', level, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Ajoute Niveau', new_level_path,
 class:"inline-flex justify-center py-2 px-4 border border-transparent 
  shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600
 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2
  focus:ring-indigo-500" %>

app/views/levels/new.html.erb
<div class="h-screen w-full flex overflow-hidden select-none">

    <%= link_to 'Retour', levels_path %>
    <main class="my-1 pt-2 pb-2 px-10 flex-1 bg-gray-200 dark:bg-black rounded-l-lg
            transition duration-500 ease-in-out overflow-y-auto">
        <br>Nouveau Niveau</h1>
        <%= render 'form', level: @level %>
    </main>
</div>

app/views/levels/show.html.erb
<div class="h-screen w-full flex overflow-hidden select-none">


<main class="my-1 pt-2 pb-2 px-10 flex-1 bg-gray-200 dark:bg-black rounded-l-lg
		transition duration-500 ease-in-out overflow-y-auto">
<br>
 <br>
 <br>
 <br><p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @level.title %>
</p>

<p>
  <strong>Adresse:</strong>
  <%= @level.slug %>
</p>

<p>
  <strong>Auteur:</strong>
  <%= @level.user_id %>
</p>

<%= link_to 'Editer', edit_level_path(@level), class:"bg-red-200" %> |
<%= link_to 'Retour', levels_path,  class:"bg-purple-200"%> | <%= link_to 'Ajoute Niveau', new_level_path,  class:"bg-blue-200"%> 
</main>
</div>