config/routes.rb
Rails.application.routes.draw do
  resources :courses
  get 'dashboard/index'
  get 'profile/index'
  resources :citytowns do
    resources :schools
      
  end
  
  resources :materials
  get 'accounted/student'
  get 'accounted/teacher'
  get 'accounted/team'
  resources :levels
  root to:'homes#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:trackable, authentication_keys: [:login]

  
  ##################  RELATIONS  ###################

  has_many :courses, dependent: :destroy
  has_many :materials
  has_many :levels
  has_many :citytowns
  has_many :schools
  has_one_attached :avatar

  #has_many :helps
  #has_many :exercices

  ################  VALIDATIONS  ###########################
def roles
  if self.role == "student"
    ########### role default value= STUDENT  ######
    validates :email, :matricule, uniqueness: true
  elsif self.role == "teacher" 
    validates :email, uniqueness: true
  elsif self.role == "city manager"
    validates :email, uniqueness: true
  elsif self.role == "team"
    validates :email, uniqueness: true
  end
  
end
  ########### UNIQUENESS  ######
    #validates :email, :matricule, uniqueness: true

  ######### PRESENTES && FORMAT  ######
    validates :phone_contact,
              :city, :school_name,
              :email,  presence: true

    validates :last_name, :first_name,
              presence: true,
              length: { maximum: 30 },
              format: { with: /\A[^0-9`!@#\$%\^&*+_=]+\z/ }

    validates :phone_contact, :whatsapp_contact,
              length: { in: 8..12 },
              numericality: { only_integer: true },
               uniqueness: true


################ NOT IMPLENETED  ###########################
  #validates :gender, presence: true
  #Birthday
   #validates :birthday, presence: true

  #enum user_gender: [:female, :male ], _default: :male

#enum user role
# define rails enum and the underlying values to use for every enum-value
#enum user_role: [:student, :teacher, :admin, :team, :support], default: :student

#enum roles: [:student, :teacher, :admin], _default: :student
################  CUSTOM ACTIONS  ###########################

def full_name
  self.full_name = "#{self.first_name} #{self.last_name}"
end

def team_sign_up
  if self.role == "team"
    self.school_name = "QH Aplatform"
  end
end

############ SLUG ###########
def slug
  self.slug = self.full_name
end

  extend FriendlyId
    friendly_id :slug, use: :slugged

  def should_generate_new_friendly_id?
    slug_changed?
  end
################  BEFORE ACTIONS  ###########################
#Delete whitespaces before and after fields, DownCase and capitalize
before_save do
  self.phone_contact      = phone_contact.strip.squeeze(" ")
  self.whatsapp_contact   = whatsapp_contact.strip.squeeze(" ")
  self.first_name         = first_name.strip.squeeze(" ").downcase.capitalize
  self.last_name          = last_name.strip.squeeze(" ").downcase.capitalize
  self.city               = city.strip.squeeze(" ").downcase.capitalize
  self.school_name        = school_name.strip.squeeze(" ").downcase.capitalize
end


################  CONSTANTE   ###########################
CLASSROOM   = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"]
SCHOOL_NAME = ["LYCEE MODERNE TIASSALE", "COLLEGE SAINT MICHEL TIASSALE", "COLLEGE PRIVE MIXTE UNION TIASSALE", "COLLÈGE NOTRE DAME DE LA PAIX TIASSALE", "COLLÈGE PRIVE LA MANNE", "Autres villes"]
CITY        = [ "Tiassalé", "N'Douci", "Agboville", "Divo", "Autres villes"]
ROLE        = ["student", "teacher", "Admin"]


################  SIGN IN PHONE NUMBR OR EMAIL  ###########################

  attr_writer :login

  def login
    @login || self.phone_contact || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_h).where(["lower(phone_contact) = :value OR lower(email) = :value", { :value => login }]).first
      elsif conditions.has_key?(:contact_phone) || conditions.has_key?(:email)
        where(conditions.to_h).first
      end
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :find_materials
  before_action :find_levels
  before_action :find_citytowns



 protected
  # If you have extra params to permit, append them to the sanitizer.
  def configure_permitted_parameters
    added_attrs = [:email, :full_name, :first_name, :last_name,
      :phone_contact, :whatsapp_contact, :matricule,
      :role, :city, :school_name, :class_name,
      :level_id, :material_id, :gender, :avatar, :slug]

    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs

  end

  private
  #enable material
    def find_materials
      @materials = Material.all
    end

    #enable level
    def find_levels
      @levels = Level.all
    end

    def find_citytowns
      @citytowns = Citytown.all
    end

end

app/views/shared/users/_sign.html.erb
<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="shadow-lg w-80 p-4 flex flex-col bg-white rounded-lg">
    <%= f.text_field :login, class:"mb-3 py-3 px-4 border border-gray-400 focus:outline-none rounded-md focus:ring-1 ring-cyan-500", hide_label: true,
        placeholder:"N° de telephone ou Adresse Email" %>
    <%= f.password_field :password, autocomplete: "current-password", class:"mb-3 py-3 px-4 border border-gray-400 focus:outline-none rounded-md focus:ring-1 ring-cyan-500",
        placeholder:"Mot de passe" %>
    <%= f.submit "Connexion", class:"w-full bg-blue-500 text-white p-3 rounded-lg font-semibold text-lg" %>
    
    <a class="text-blue-400 text-center my-2">Mot de passe oublie?</a>
    <hr />
       Inscrivez-vous gratuitement, C'est simple
       <%= link_to accounted_student_path  do %> 
        <button class="w-full bg-green-400 mt-8 mb-4 text-white p-3 rounded-lg
                font-semibold text-lg">Inscription élève</button>
                <a href="#" class="text-red-500 text-center my-2">Devenir Prof Partenaire</a>
       <% end %>
  </div>
<% end %>

app/views/shared/users/_sign_in.html.erb
<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="shadow-lg w-80 p-4 flex flex-col bg-white rounded-lg">
    <%= f.text_field :login, class:"mb-3 py-3 px-4 border border-gray-400 focus:outline-none rounded-md focus:ring-1 ring-cyan-500", hide_label: true,
        placeholder:"N° de telephone ou Adresse Email" %>
    <%= f.password_field :password, autocomplete: "current-password", class:"mb-3 py-3 px-4 border border-gray-400 focus:outline-none rounded-md focus:ring-1 ring-cyan-500",
        placeholder:"Mot de passe" %>
    <%= f.submit "Connexion", class:"w-full bg-blue-500 text-white p-3 rounded-lg font-semibold text-lg" %>
    
    <a class="text-blue-400 text-center my-2">Mot de passe oublie?</a>
    <hr />
       Inscrivez-vous gratuitement, C'est simple
       <%= link_to accounted_student_path  do %> 
        <button class="w-full bg-green-400 mt-8 mb-4 text-white p-3 rounded-lg
                font-semibold text-lg">Inscription élève</button>
                <a href="#" class="text-red-500 text-center my-2">Devenir Prof Partenaire</a>
       <% end %>
  </div>
<% end %>

app/views/shared/users/_sign_up_student.html.erb
<%= content_for @title=" Inscription Eleves" %>
<div class="container" id="wrap">
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3">
            <span class="items-center">
                <legend>Inscription</legend>
                <h4 class="font-semibold mb-2">Inscrivez-vous gratuitement, C'est simple.</h4>
            </span>

            <%= bootstrap_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
                <%= render "devise/shared/error_messages", resource: resource %>
                <div class="row">
                    <!-- User first and last name-->
                    <div class="col-xs-6 col-md-6 my-1">
                        <%= f.text_field :first_name, hide_label: true, class:"form-control input-lg",
                                placeholder:"Nom :", autofocus: true %>
                    </div>
                    <div class="col-xs-6 col-md-6 my-1">
                        <%= f.text_field :last_name, hide_label: true, class:"form-control input-lg",
                        placeholder:"Prénom :" %>
                    </div>
                </div>

                 <!-- user email-->
                <%= f.email_field :email, id:"studentEmail", hide_label: true, 
                    class:"form-control input-lg ",placeholder:"Adresse email:",
                    help:"Pas d'email, Utilise ton N° tel  + @gmail.com." %>

                <!-- Matricule-->
                <%= f.text_field :matricule, hide_label: true, class:"form-control input-lg",
                placeholder:"N° Matricule National :" %>

                <!-- city-->
                <div class="options md:flex text-sm items-center text-gray-700 mb-2 ">    
                    <%= f.select :city, @citytowns.map { |city| [city.title, city.id] }, label: "Ville:", label_class:"font-semibold",
                    wrapper: {class:"md:w-1/3 border border-gray-200 focus:outline-none focus:border-gray-500"} %>
            
                    <!-- school name-->
                    <%= f.select :school_name, User::SCHOOL_NAME, label: "Ecole: ", label_class:"font-semibold",
                    wrapper: { class: "md:w-1/3 border border-gray-200 focus:outline-none 
                    focus:border-gray-500"} %>      
            
                    <%= f.select :level_id, @levels.map { |l| [l.title, l.id] }, label: "Niveau: ", label_class:"font-semibold",
                    wrapper: {class:"md:w-1/3 border border-gray-200 focus:outline-none focus:border-gray-500"} %>
                </div>
            
                <!-- phone contact-->
                <%= f.phone_field :phone_contact, class:"form-control  input-lg ",
                    placeholder:"N° téléphone :", hide_label: true, id:"studentContact",
                    help:"Numéro de téléphone Ivoirien."  %>
                
                <!-- phone contact-->
                <%= f.phone_field :whatsapp_contact, class:"form-control  input-lg my-1 ",
                    placeholder:"N° téléphone WhatsApp :", hide_label: true , 
                    help:"Ajouter votre numéro whatsapp, pas Obligatoire!" %>

                    <!-- password section-->
                <%= f.password_field :password, hide_label: true, class:"form-control  input-lg ", 
                    help:"Un bon mot de passe doit avoir plus de 8 caractères",
                    placeholder:"Mot de passe :" %>

                <!-- Passwword confirm -->
                <%= f.password_field :password_confirmation, 
                    hide_label: true, class:"form-control md:input-lg lg:input-lg my-1 ",
                    placeholder:"Confirmez votre mot de passe :", 
                    help:"retaper le mot de passe" %>           
                

                <%= f.hidden_field :role, value:"student" %>

                <!-- Corporate Msg-->
                <span class="help-block">
                    En cliquant sur Créer mon compte, votre compte sera créé et vous aurez une semaine offerte.
                </span>
                <div class="actions">
                    <%= f.submit "Créer mon compte", class:"btn btn-lg btn-primary btn-block signup-btn" %>
                </div>
            <% end %>

        </div>
    </div>
</div>

app/views/shared/users/_sign_up_teacher.html.erb
<%= content_for @title=" Inscription Professeur" %>

<div class="container" id="wrap">
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3">
            <span class="items-center">
                <legend>Inscription</legend>
                <h4 class="font-semibold mb-2">Inscrivez-vous gratuitement, C'est simple.</h4>
            </span>

            <%= bootstrap_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
                <%= render "devise/shared/error_messages", resource: resource %>
                <div class="row mb-2">
                    <!-- User first and last name-->
                    <div class="col-xs-6 col-md-6 my-1">
                        <%= f.text_field :first_name,
                        hide_label: true, class:"form-control input-lg",
                        placeholder:"Nom :", autofocus: true %>
                    </div>
                    <div class="col-xs-6 col-md-6 my-1">
                        <%= f.text_field :last_name,
                        hide_label: true, class:"form-control  input-lg",
                        placeholder:"Prénom :" %>
                    </div>
                </div>
                <!-- city-->
                <div class="options md:flex text-sm items-center text-gray-700 mb-2">    
                    <%= f.select :city, @citytowns.map { |city| [city.title, city.id] }, label: "Ville:",label_class:"font-semibold",
                    wrapper: {class:"md:w-1/3 border border-gray-200 focus:outline-none focus:border-gray-500"} %>
            
                    <!-- school name-->
                    <%= f.select :school_name, User::SCHOOL_NAME, label: "Ecole: ", label_class:"font-semibold",
                    wrapper: { class: "md:w-1/3 border border-gray-200 focus:outline-none 
                    focus:border-gray-500"} %>      
            
                    <%= f.select :material_id, @materials.map { |m| [m.title, m.id] }, label: "Discipline: ", label_class:"font-semibold",
                    wrapper: {class:"md:w-1/3 border border-gray-200 focus:outline-none focus:border-gray-500"} %>
                </div>
                
               
            
                <!-- phone contact-->
                <%= f.phone_field :phone_contact, class:"form-control  input-lg ",
                    placeholder:"N° téléphone :", hide_label: true, id:"studentContact",
                    help:"Numéro de téléphone Ivoirien à 10 chiffres."  %>

                <!-- phone contact-->
                <%= f.phone_field :whatsapp_contact, class:"form-control  input-lg my-1 ",
                placeholder:"N° téléphone WhatsApp :", hide_label: true , 
                help:"Ajouter votre numéro whatsapp, pas Obligatoire!" %>

                <!-- user email-->
                <%= f.email_field :email, id:"studentEmail", hide_label: true, 
                class:"form-control input-lg  mb-2",placeholder:"Adresse email:" %>
                
                <!-- role-->
                <%= f.hidden_field :role, value:"teacher" %>
                    <!-- password section-->
                <%= f.password_field :password, hide_label: true, class:"form-control  input-lg ", 
                help:"Un bon mot de passe doit avoir plus de 8 caractères",
                placeholder:"Mot de passe :" %>

                <!-- Passwword confirm -->
                <%= f.password_field :password_confirmation, 
                hide_label: true, class:"form-control md:input-lg lg:input-lg my-1 ",
                placeholder:"Confirmez votre mot de passe :", 
                help:"retaper le mot de passe" %>



                <!-- Corporate Msg-->
                <span class="help-block">
                    En cliquant sur Créer mon compte, votre compte sera automaquement créé. 
                
                    <br />
                     Notre service Assistant vous contacter dans les 24h pour valider votre compte.
                </span>
                <div class="actions">
                    <%= f.submit "Créer mon compte", class:"btn btn-lg btn-primary btn-block signup-btn" %>
                </div>
            <% end %>

        </div>
    </div>
</div>